### ISSUE TITLE
Serial connection does not work properly

### ISSUE THREAD

**Issue by J4nn1K** [J4nn1K/demonstration-interface#1]
Sometimes the byte sequence from the serial port can't be decoded:
```
Traceback (most recent call last):
  File "scripts/test_trigger.py", line 20, in <module>
    main()
  File "scripts/test_trigger.py", line 8, in main
    trigger.calibrate()
  File "/home/jannik/Repos/demonstration-interface/src/components/trigger.py", line 43, in calibrate
    value = self.get_adc_value()
  File "/home/jannik/Repos/demonstration-interface/src/components/trigger.py", line 53, in get_adc_value
    line = self.read_serial()
  File "/home/jannik/Repos/demonstration-interface/src/components/trigger.py", line 87, in read_serial
    line = self.ser.readline().decode().rstrip()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf8 in position 8: invalid start byte
```

**Comment by J4nn1K** [comment]
When the node is terminated this method is executed:
```
def close_serial(self):
    self.ser.reset_input_buffer()
    self.ser.reset_output_buffer()
    self.ser.close()
    log.info(f'Connection closed')
```
The next time the node is started it receives no bytes via the serial port.
When the connection is not closed using `ser.close` and the node is started, it works.

**Comment by J4nn1K** [comment]
Look into this: https://stackoverflow.com/questions/36869394/reset-an-open-serial-port
